logging:
  path: /var/logs
  file: bookworm.log
  level:
    root: INFO
    org.springframework.security: INFO

---

spring:
    profiles: production
    datasource:
       url: jdbc:mysql://localhost:3306/readinglist
       username: root
       password: root
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
           ddl-auto: none
