logging:
  path: /var/logs
  file: bookworm.log
  level:
    root: WARN
    org.springframework.security: WARN

---

spring:
    profiles: production
    datasource:
       url: jdbc:postgresql://localhost:5432/readinglist
       username: sa
       password:
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
           ddl-auto: none